helpdesk/helpdesk/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('helpdesk_app.urls')),
]

helpdesk/helpdesk_app/urls.py
from django.urls import path
from . import views
from helpdesk_app import views_auth


urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create_problem, name='create-problem'),
    path('list/', views.problem_list, name='problem-list'),
    path('problem/<int:problem_id>/', views.problem_detail, name='problem-detail'),
    path('login/', views_auth.login_view, name='login'),
    path('logout/', views_auth.logout_view, name='logout'),
]


helpdesk/helpdesk_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.models import Group

reception_group, created = Group.objects.get_or_create(name='Reception')
tester_group, created = Group.objects.get_or_create(name='Tester')


PRIORITY_CHOICES = [
    ('low', 'Низкий'),
    ('medium', 'Средний'),
    ('high', 'Высокий'),
]

STATUS_CHOICES = [
    ('new', 'Новый'),
    ('in_progress', 'В процессе'),
    ('resolved', 'Решено'),
    ('confirmed', 'Подтверждено'),
]


class Problem(models.Model):
    name = models.CharField(max_length=255)
    phone = models.CharField(max_length=15)
    email = models.EmailField()
    description = models.TextField()
    actions = models.TextField(blank=True)
    priority = models.CharField(max_length=10, choices=PRIORITY_CHOICES)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='new')
    assigned_user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='assigned_problems')
    resolved_user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='resolved_problems')

helpdesk/helpdesk_app/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Problem


class ProblemForm(forms.ModelForm):
    reception_user = forms.ModelChoiceField(
        queryset=User.objects.filter(groups__name='Reception'),
        required=False,
        widget=forms.Select,
        label='Перенаправить заявку в группу Reception'
    )

    class Meta:
        model = Problem
        fields = ['name', 'phone', 'email', 'description', 'priority', 'assigned_user', 'reception_user']
        labels = {
            'name': 'Имя',
            'phone': 'Телефон',
            'email': 'Email',
            'description': 'Описание',
            'priority': 'Приоритет',
            'assigned_user': 'Назначенный пользователь',
        }

helpdesk/helpdesk_app/views.py
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from .forms import ProblemForm
from .models import Problem
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import get_object_or_404


def index(request):
    if request.user.is_authenticated:
        return redirect('problem-list')
    else:
        return render(request, 'helpdesk_app/index.html')


def create_problem(request):
    if request.method == 'POST':
        form = ProblemForm(request.POST)
        if form.is_valid():
            problem = form.save(commit=False)
            assigned_user = form.cleaned_data['assigned_user']
            problem.assigned_user = assigned_user
            problem.save()
            return redirect('index')
    else:
        form = ProblemForm()
    return render(request, 'helpdesk_app/create_problem.html', {'form': form})


def problem_list(request):
    user = request.user
    if user.is_authenticated:
        if user.groups.filter(name='Reception').exists():
            problems = Problem.objects.filter(assigned_user=user)
        else:
            problems = Problem.objects.filter(assigned_user=user)
        return render(request, 'helpdesk_app/problem_list.html', {'problems': problems})
    else:
        return redirect('index')


def problem_detail(request, problem_id):
    problem = get_object_or_404(Problem, pk=problem_id)
    users = User.objects.all()
    if request.method == 'POST':
        assigned_user_id = request.POST.get('assigned_user')
        if assigned_user_id:
            new_assigned_user = get_object_or_404(User, id=assigned_user_id)
            problem.assigned_user = new_assigned_user
        problem.actions = request.POST.get('actions', '')
        new_status = request.POST.get('status', 'new')
        problem.status = new_status
        problem.save()
        return HttpResponseRedirect(reverse('problem-list'))
    return render(request, 'helpdesk_app/problem_detail.html', {'problem': problem, 'users': users})



helpdesk/helpdesk_app/templates/helpdesk_app/create_problem.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Создать проблему</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/common.css' %}">
</head>
<body>
    <div class="container">
        <h1>Создать проблему</h1>
        <form method="post">
            {% csrf_token %}
            <div class="form-field">
                <label for="id_name">{{ form.name.label }}</label>
                {{ form.name }}
            </div>
            <div class="form-field">
                <label for="id_phone">{{ form.phone.label }}</label>
                {{ form.phone }}
            </div>
            <div class="form-field">
                <label for="id_email">{{ form.email.label }}</label>
                {{ form.email }}
            </div>
            <div class="form-field">
                <label for="id_description">{{ form.description.label }}</label>
                {{ form.description }}
            </div>
            <div class="form-field">
                <label for="id_priority">{{ form.priority.label }}</label>
                {{ form.priority }}
            </div>
            <div class="form-field">
                <label for="id_assigned_user">{{ form.assigned_user.label }}</label>
                {{ form.assigned_user }}
            </div>
            <button class="submit-button" type="submit">Отправить</button>
        </form>
    </div>
</body>
</html>



helpdesk/helpdesk_app/templates/helpdesk_app/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>HelpDesk</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>
    <div class="container">
        <p>Добро пожаловать в HelpDesk!</p>
        <p>Чтобы авторизоваться, нажмите <a href="/login">сюда</a></p>
        <p><a href="{% url 'create-problem' %}">Создать проблему</a></p>
    </div>
</body>
</html>

helpdesk/helpdesk_app/templates/helpdesk_app/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Авторизация</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
</head>
<body>
    <div class="container">
        <div class="row justify-content-center mt-5">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header">
                        <h1 class="text-center">Авторизация</h1>
                    </div>
                    <div class="card-body">
                        <form action="" method="post">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="email">Логин</label>
                                <input name="email" type="email" class="form-control" id="email" required>
                            </div>
                            <div class="form-group">
                                <label for="password">Пароль</label>
                                <input name="password" type="password" class="form-control" id="password">
                            </div>
                            {% if message %}
                            <div class="alert alert-danger" role="alert">
                                {{ message }}
                            </div>
                            {% endif %}
                            <button type="submit" class="btn btn-primary btn-block">Войти</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

helpdesk/helpdesk_app/templates/helpdesk_app/problem_detail.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Подробнее о проблеме</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        body {
            margin: 20px;
        }
        .container {
            max-width: 600px;
        }
    </style>
        <script>
        document.addEventListener("DOMContentLoaded", function () {
            var statusSelect = document.getElementById("status");
            var actionsTextarea = document.getElementById("actions");
            var savedStatus = statusSelect.getAttribute("data-saved-status");
            var savedActions = actionsTextarea.getAttribute("data-saved-actions");
            statusSelect.value = savedStatus;
            actionsTextarea.value = savedActions;
        });
    </script>
</head>
<body>
    <div class="container">
        <h1 class="mt-4">Подробнее о проблеме</h1>
<form method="post" class="mt-4">
    {% csrf_token %}
    <div class="form-group">
        <label for="status">Статус:</label>
        <select name="status" id="status" class="form-control" data-saved-status="{{ problem.status }}">
            <option value="new">Новый</option>
            <option value="in_progress">В процессе</option>
            <option value="resolved">Решено</option>
            <option value="confirmed">Подтвержденный</option>
        </select>
    </div>
    <div class="form-group">
        <label for="actions">Действия:</label>
        <textarea name="actions" id="actions" class="form-control" data-saved-actions="{{ problem.actions }}"></textarea>
    </div>
  <label for="assigned_user">Перенаправить:</label>
  <select name="assigned_user" id="assigned_user">
    {% for user in users %}
      <option value="{{ user.id }}" {% if user.id == problem.assigned_user.id %}selected{% endif %}>{{ user.username }}</option>
    {% endfor %}
  </select>
    <button type="submit" class="btn btn-primary">Сохранить</button>
</form>


        <hr>

        <p><strong>Имя:</strong> {{ problem.name }}</p>
        <p><strong>Телефон:</strong> {{ problem.phone }}</p>
        <p><strong>Email:</strong> {{ problem.email }}</p>
        <p><strong>Описание:</strong> {{ problem.description }}</p>
        <p><strong>Приоритет:</strong> {{ problem.get_priority_display }}</p>
        <p><strong>Статус:</strong> {{ problem.status }}</p>
        <p><strong>Действия:</strong> {{ problem.actions }}</p>
        <p><strong>Время создания:</strong> {{ problem.created_at }}</p>
        <a href="{% url 'problem-list' %}" class="btn btn-secondary">Назад</a>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

helpdesk/helpdesk_app/templates/helpdesk_app/problem_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Список проблем</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    <div class="container">
        <h1 class="mt-4">Список проблем</h1>
        <a href="/logout" class="btn btn-danger mt-2">Выйти</a>
        <table class="table mt-4">
            <thead>
                <tr>
                    <th scope="col">Имя</th>
                    <th scope="col">Телефон</th>
                    <th scope="col">Email</th>
                    <th scope="col">Описание</th>
                    <th scope="col">Приоритет</th>
                    <th scope="col">Назначенный пользователь</th>
                </tr>
            </thead>
            <tbody>
                {% for problem in problems %}
                    <tr>
                        <td><a href="{% url 'problem-detail' problem.id %}">{{ problem.name }}</a></td>
                        <td>{{ problem.phone }}</td>
                        <td>{{ problem.email }}</td>
                        <td>{{ problem.description }}</td>
                        <td>{{ problem.priority }}</td>
                        <td>{{ problem.assigned_user }}</td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="6">Нет проблем</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>